In [1]:
import data, main, ML_engine, optimizer, QC_engine

In [2]:
from deepmd.calculator import DP

2022-03-14 18:22:09.520942: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-14 18:22:09.520988: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
setting = {'basis':'6-31g', 'spin':0, 'xc':False, 'restricted':True, 'spin':0}
geo = main.MLgeomopt(qc_engine='pyscf', ml_engine='deepmd', work_path='./', xyz_path='./water.xyz',**setting)
geo.opt_algorithm = 'bfgs'
geo.kernel()

OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-15
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #216: KMP_AFFINITY: x2APIC ids not unique.
OMP: Info #216: KMP_AFFINITY: decoding legacy APIC ids.
OMP: Info #216: KMP_AFFINITY: legacy APIC ids not unique.
OMP: Info #220: KMP_AFFINITY: parsing /proc/cpuinfo.
OMP: Info #157: KMP_AFFINITY: 16 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #192: KMP_AFFINITY: 1 socket x 8 cores/socket x 2 threads/core (8 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS p


			###########################################
			###     Optimization cycle:     1       ###
			###########################################
			


2022-03-14 18:22:13.402459: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-14 18:22:13.402500: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 1)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-03-14 18:22:16.833697: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

      Step     Time          Energy          fmax
BFGS:    0 18:24:35    -4126.198598         2.069553
BFGS:    1 18:24:35    -4126.460022         2.855430
BFGS:    2 18:24:35    -4127.782140         4.439503
BFGS:    3 18:24:35    -4131.259575         4.333813
BFGS:    4 18:24:35    -4133.999157         3.116395
BFGS:    5 18:24:35    -4135.769505         1.963930
BFGS:    6 18:24:35    -4136.772291         1.184320
BFGS:    7 18:24:35    -4137.255704         0.817037
BFGS:    8 18:24:35    -4137.400782         0.865229
BFGS:    9 18:24:35    -4137.452397         0.892986
BFGS:   10 18:24:35    -4137.494449         0.926870
BFGS:   11 18:24:35    -4137.575885         0.971115
BFGS:   12 18:24:35    -4137.711975         0.899719
BFGS:   13 18:24:35    -4137.869805         0.735554
BFGS:   14 18:24:35    -4138.102158         0.852496
BFGS:   15 18:24:35    -4138.441521         1.077436
BFGS:   16 18:24:35    -4138.732150         1.500955
BFGS:   17 18:24:35    -4139.098062         2.692

OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10480 thread 16 bound to OS proc set 0
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10482 thread 17 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10483 thread 18 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10485 thread 20 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10484 thread 19 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10487 thread 22 bound to OS proc set 12
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10488 thread 23 bound to OS proc set 14
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10486 thread 21 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10489 thread 24 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10491 thread 26 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10490 thread 25 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 9759 tid 10492 thread 27 bound to OS proc set 7
OMP: Info #25

BFGS:   29 18:24:35    -4209.653226       100.883745
BFGS:   30 18:24:35    -4210.084505       169.053223
BFGS:   31 18:24:35    -4207.468176        55.992427
BFGS:   32 18:24:35    -4210.496713        64.575984
BFGS:   33 18:24:35    -4203.051030        40.155422
BFGS:   34 18:24:35    -4214.929781        14.560381
BFGS:   35 18:24:35    -4214.940533         9.487255
BFGS:   36 18:24:35    -4215.002439         0.990875
BFGS:   37 18:24:35    -4215.005393         0.970251
BFGS:   38 18:24:35    -4214.995881         7.818704
BFGS:   39 18:24:35    -4215.013575         0.806043
BFGS:   40 18:24:35    -4215.019806         0.590615
BFGS:   41 18:24:35    -4215.031435         0.377097
BFGS:   42 18:24:35    -4215.031808         0.356949
BFGS:   43 18:24:35    -4215.003917         6.963792
BFGS:   44 18:24:35    -4215.032347         0.233029
BFGS:   45 18:24:35    -4215.032584         0.210979
BFGS:   46 18:24:35    -4215.033392         0.232218
BFGS:   47 18:24:35    -4215.033688         0.

In [5]:
from pyscf import gto,scf
from pyscf.data.nist import BOHR
import numpy as np

mol = gto.Mole(atom='''
H 0 0 0
H 0 0 0.5''', basis='6-31g').build()
coord = mol.atom_coords()*BOHR
coord[1,2] = 1.0
print(mol.atom_coords()/BOHR)

mf = scf.RHF(mol)
mf.kernel()

[[0.         0.         0.        ]
 [0.         0.         1.78553241]]
converged SCF energy = -1.05802481296927


-1.0580248129692664

In [6]:
mol = mol.set_geom_(coord)
print(mol.atom_coords()*BOHR)
mf.kernel()

[[0. 0. 0.]
 [0. 0. 1.]]
SCF not converged.
SCF energy = -0.845502706552932


-0.8455027065529318