In [1]:
from MQGO import data, main, ML_engine, optimizer, QC_engine 
from deepmd.calculator import DP
import subprocess
import numpy as np
import json

2022-04-23 18:44:46.325293: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:44:46.325432: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
d_steps = [3000]
tot_steps = [4000]
subprocess.run('cp water0.xyz water.xyz', shell=True)

index = 0
for ii in range(0,len(d_steps)):
    for jj in range(0,len(tot_steps)):
        js_setting = {}
        with open('./input0.json', 'r') as file:
            json_setting = json.load(file)
            print('after remake json: ',json_setting['learning_rate']['decay_steps'])
            
        json_setting['learning_rate']['decay_steps'] = d_steps[ii]
        json_setting['training']['numb_steps'] = tot_steps[jj]
        print('ii,jj:',ii,jj)
        print('before make json: ',json_setting['learning_rate']['decay_steps'])
        with open('./input.json', 'w') as js:
            json.dump(json_setting, js, indent=4)
        
        setting = {'basis':'6-31g', 'spin':0, 'xc':None, 'restricted':True, 'verbose':0}
        geo = main.MLgeomopt(qc_engine='pyscf', ml_engine='deepmd', work_path='./', xyz_path='./water.xyz',**setting)
        geo.opt_algorithm = 'lbfgs'
        geo.debug = True
        geo.kernel()
        
        Opt = optimizer.Optimizer(xyz_path="water0.xyz",
									work_path="./",
									ml_engine='deepmd',
									outter_cycle=1,
									algorithm='lbfgs',
									max_opt_cycle=100)
        atom0 = Opt.ase_read_xyz()
        atom0.calc = DP(model='graph.pb')
        print(atom0.get_potential_energy())
        force0_ml = atom0.get_forces()

        forces = np.loadtxt('raw/force.raw')
        force0_qc = forces[0].reshape((6,3))

        delta = force0_qc-force0_ml
        with open('debug_diff_force.txt', 'a') as file:
            file.write('24.18f\n'%atom0.get_potential_energy())
            for i in range(0, len(force0_qc)):
                for j in range(0, 3):
                    file.write('%24.18f'%delta[i][j])
                file.write('\n')
            file.write('\n')
            
        print('after dp: ',json_setting['learning_rate']['decay_steps'])
        subprocess.run('cp water0.xyz water.xyz', shell=True)
        # subprocess.run('rm input.json', shell=True)

after remake json:  4000
ii,jj: 0 0
before make json:  3000


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpnoe8grd1
max_memory 21438 MB (current use 360 MB)
Set gradient conv threshold to 1e-06
init E= -151.415122555484
  HOMO = -0.458914611898626  LUMO = 0.101611688525233
cycle= 1 E= -151.868630726732  delta_E= -0.454  |g|= 0.597  |ddm|= 1.64
  HOMO = -0.400323409471753  LUMO = 0.194953131082893
cycle= 2 E= -151.927771207762  delta_E= -0.0591  |g|= 0.357  |ddm|= 0.608
  HOMO = -0.499862289875179  LUMO = 0.180933357043683
cycle= 3 E= -151.95036021667  delta_E= -0.0226  |g|= 0.0355  |ddm|= 0.229


OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-11
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #216: KMP_AFFINITY: x2APIC ids not unique.
OMP: Info #216: KMP_AFFINITY: decoding legacy APIC ids.
OMP: Info #216: KMP_AFFINITY: legacy APIC ids not unique.
OMP: Info #220: KMP_AFFINITY: parsing /proc/cpuinfo.
OMP: Info #157: KMP_AFFINITY: 12 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #192: KMP_AFFINITY: 1 socket x 6 cores/socket x 2 threads/core (6 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS p

  HOMO = -0.497612927938677  LUMO = 0.187865526656965
cycle= 4 E= -151.950856808118  delta_E= -0.000497  |g|= 0.00594  |ddm|= 0.0375
  HOMO = -0.498863887981174  LUMO = 0.187642464715898
cycle= 5 E= -151.950875581763  delta_E= -1.88e-05  |g|= 0.000688  |ddm|= 0.00925
  HOMO = -0.498920556933575  LUMO = 0.187620019572829
cycle= 6 E= -151.950875817958  delta_E= -2.36e-07  |g|= 0.000198  |ddm|= 0.00111
  HOMO = -0.498975213195492  LUMO = 0.187616477545118
cycle= 7 E= -151.950875827637  delta_E= -9.68e-09  |g|= 5.74e-05  |ddm|= 0.000157
  HOMO = -0.498963904179647  LUMO = 0.187615348330252
cycle= 8 E= -151.950875829917  delta_E= -2.28e-09  |g|= 1.17e-05  |ddm|= 0.00012
  HOMO = -0.498961965070038  LUMO = 0.187614886419037
cycle= 9 E= -151.95087583003  delta_E= -1.13e-10  |g|= 1.35e-06  |ddm|= 3.23e-05
  HOMO = -0.498961881531363  LUMO = 0.187614670626288
cycle= 10 E= -151.950875830031  delta_E= -6.25e-13  |g|= 2.51e-07  |ddm|= 2.62e-06
  HOMO = -0.498961918333598  LUMO = 0.18761465484597
E

2022-04-23 18:44:49.726100: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:44:49.726245: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:44:54.339216: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:44:54.353064: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.63802  1.5711   1.76   ]
 [26.36198  1.5711   1.76   ]
 [ 3.95828  2.55412  1.74392]
 [ 2.63613  1.66728  1.76493]
 [26.09174  0.99418  2.56104]
 [26.0955   0.9908   0.96072]]


2022-04-23 18:46:20.063419: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:46:20.077779: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-04-23 18:46:20.077906: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Deng-PC): /proc/driver/nvidia/version does not exist


       Step     Time          Energy          fmax
LBFGS:    0 18:46:20    -4134.545103   4.41573e+00
LBFGS:    1 18:46:20    -4135.741622   5.23433e+00
LBFGS:    2 18:46:20    -4133.599016   5.59044e+00
LBFGS:    3 18:46:20    -4134.144386   6.85933e+00
LBFGS:    4 18:46:20    -4133.538228   4.59023e+00
LBFGS:    5 18:46:20    -4133.557083   3.03756e+00
LBFGS:    6 18:46:20    -4133.551718   4.21133e+00
LBFGS:    7 18:46:20    -4133.558376   3.67767e+00
LBFGS:    8 18:46:20    -4133.543948   4.57562e+00
LBFGS:    9 18:46:20    -4133.533496   4.94516e+00
LBFGS:   10 18:46:20    -4133.480824   6.05020e+00
LBFGS:   11 18:46:20    -4133.671878   7.72610e+00
LBFGS:   12 18:46:20    -4133.478568   6.07701e+00
LBFGS:   13 18:46:20    -4133.476310   6.09254e+00
LBFGS:   14 18:46:20    -4133.106630   9.51061e+00
LBFGS:   15 18:46:20    -4133.072594   9.33093e+00
LBFGS:   16 18:46:21    -4133.169345   6.62579e+00
LBFGS:   17 18:46:21    -4133.074424   9.32651e+00
LBFGS:   18 18:46:21    -4133.0

OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21760 thread 12 bound to OS proc set 0
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21762 thread 13 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21763 thread 14 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21764 thread 15 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21765 thread 16 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21766 thread 17 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21767 thread 18 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21768 thread 19 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21769 thread 20 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21770 thread 21 bound to OS proc set 7
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21771 thread 22 bound to OS proc set 9
OMP: Info #254: KMP_AFFINITY: pid 21350 tid 21772 thread 23 bound to OS proc set 11


LBFGS:   24 18:46:21    -4132.283940   1.71841e+00
LBFGS:   25 18:46:21    -4132.281249   1.51544e+00
LBFGS:   26 18:46:21    -4132.284929   1.32262e+00
LBFGS:   27 18:46:21    -4132.283761   1.52050e+00
LBFGS:   28 18:46:21    -4132.285233   1.46875e+00
LBFGS:   29 18:46:21    -4132.281879   1.53779e+00
LBFGS:   30 18:46:21    -4132.279474   1.53486e+00
LBFGS:   31 18:46:21    -4132.269119   1.38907e+00
LBFGS:   32 18:46:21    -4132.256595   1.21522e+00
LBFGS:   33 18:46:21    -4132.244316   7.76259e-01
LBFGS:   34 18:46:21    -4132.238970   3.20298e-01
LBFGS:   35 18:46:21    -4132.238128   2.24691e-01
LBFGS:   36 18:46:21    -4132.237937   2.14383e-01
LBFGS:   37 18:46:21    -4132.237445   1.86798e-01
LBFGS:   38 18:46:21    -4132.236881   2.43011e-01
LBFGS:   39 18:46:21    -4132.236198   3.04609e-01
LBFGS:   40 18:46:21    -4132.235745   2.33541e-01
LBFGS:   41 18:46:21    -4132.235492   9.08851e-02
LBFGS:   42 18:46:21    -4132.235446   1.29311e-02
LBFGS:   43 18:46:21    -4132.2

2022-04-23 18:46:22.247923: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:46:22.248065: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:46:26.781508: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:46:26.794936: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081422  1.93083333  1.75628331]
 [26.18307485  1.18536328  1.76058668]
 [ 3.62036208  2.73996061  1.74338806]
 [ 3.2012537   1.12170606  1.76917863]
 [26.20932033  1.24793207  2.59375097]
 [26.15682482  1.12278465  0.92742235]]
       Step     Time          Energy          fmax
LBFGS:    0 18:48:13    -4133.757312   8.16722e+00
LBFGS:    1 18:48:13    -4139.477741   1.59372e+01
LBFGS:    2 18:48:13    -4132.083303   2.03499e+00
LBFGS:    3 18:48:13    -4131.952552   2.43709e-01
LBFGS:    4 18:48:13    -4131.950473   2.45640e-02
LBFGS:    5 18:48:13    -4131.950461   2.67773e-02
LBFGS:    6 18:48:13    -4131.950485   6.92001e-02
LBFGS:    7 18:48:13    -4131.950457   5.37319e-04
LBFGS:    8 18:48:13    -4131.950457   8.90773e-05


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad =

/home/dgg95223/ase/ase/io/extxyz.py:1003: UserWarning: write_xyz() overwriting array "forces" present in atoms.arrays with stored results from calculator
  'from calculator'.format(key))


--------------- RHF gradients ---------------
         x                y                z
0 O     0.0000006013    -0.0000002603     0.0000001805
1 O    -0.0000028219    -0.0000024273    -0.0000000195
2 H     0.0081727493     0.0315579698    -0.0005030310
3 H    -0.0081733427    -0.0315577052     0.0005028514
4 H     0.0010251872     0.0024418967     0.0324975039
5 H    -0.0010223733    -0.0024394736    -0.0324974853
----------------------------------------------


******** <class 'pyscf.grad.rhf.Gradients'> for <class 'pyscf.scf.hf.RHF'> ********
max_memory 21438 MB (current use 793 MB)
--------------- RHF gradients ---------------
         x                y                z
0 O     0.0000006013    -0.0000002603     0.0000001805
1 O    -0.0000028219    -0.0000024273    -0.0000000195
2 H     0.0081727493     0.0315579698    -0.0005030310
3 H    -0.0081733427    -0.0315577052     0.0005028514
4 H     0.0010251872     0.0024418967     0.0324975039
5 H    -0.0010223733    -0.0024394736  

2022-04-23 18:48:14.916958: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:48:14.917097: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:48:19.705206: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:48:19.718389: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081449  1.930832    1.75628333]
 [26.18307506  1.18536372  1.76058628]
 [ 3.64967455  2.85314263  1.74158425]
 [ 3.17194096  1.00852537  1.77098242]
 [26.21299183  1.25668481  2.71029627]
 [26.15315312  1.11403146  0.81087745]]
       Step     Time          Energy          fmax
LBFGS:    0 18:50:22    -4132.613702   1.68133e+00
LBFGS:    1 18:50:22    -4132.832016   2.82417e+00
LBFGS:    2 18:50:22    -4132.521115   4.72565e-01
LBFGS:    3 18:50:22    -4132.514928   1.02702e-01
LBFGS:    4 18:50:22    -4132.514608   3.39102e-03
LBFGS:    5 18:50:22    -4132.514608   5.28048e-03
LBFGS:    6 18:50:22    -4132.514609   1.15272e-02
LBFGS:    7 18:50:22    -4132.514608   7.20712e-04
LBFGS:    8 18:50:22    -4132.514608   4.37857e-04


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad =

2022-04-23 18:50:23.202798: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:50:23.202938: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:50:27.988393: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:50:28.002055: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081375  1.93083281  1.75628332]
 [26.18307473  1.185363    1.76058654]
 [ 3.6425575   2.82566057  1.74202224]
 [ 3.17905875  1.03600662  1.77054444]
 [26.21210077  1.25456051  2.68200644]
 [26.15404452  1.11615648  0.83916702]]
       Step     Time          Energy          fmax
LBFGS:    0 18:52:52    -4131.578906   7.91404e-02
LBFGS:    1 18:52:52    -4131.579434   1.56629e-01
LBFGS:    2 18:52:52    -4131.578724   8.47488e-04
LBFGS:    3 18:52:52    -4131.578724   1.33835e-03
LBFGS:    4 18:52:52    -4131.578724   2.53017e-03
LBFGS:    5 18:52:52    -4131.578724   2.53996e-04


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpfe6uf6i8
max_memory 21438 MB (current use 1153 M

2022-04-23 18:52:54.019841: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:52:54.019976: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:52:58.641705: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:52:58.655041: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081291  1.93083104  1.75628335]
 [26.18307457  1.18536266  1.76058594]
 [ 3.64285027  2.82679025  1.74200423]
 [ 3.17876683  1.03487871  1.77056241]
 [26.21213712  1.25464716  2.68315824]
 [26.15400832  1.11607017  0.83801582]]
       Step     Time          Energy          fmax
LBFGS:    0 18:55:44    -4132.870434   5.46265e-02
LBFGS:    1 18:55:44    -4132.870684   1.06613e-01
LBFGS:    2 18:55:44    -4132.870345   1.52654e-03
LBFGS:    3 18:55:44    -4132.870345   5.36325e-03
LBFGS:    4 18:55:44    -4132.870345   9.32164e-05


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpi3rg8bm6
max_memory 21438 MB (current use 1291 MB)
Set gradient conv threshold to 1e-06
init E= 17.

2022-04-23 18:55:45.208910: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:55:45.209055: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:55:49.670100: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:55:49.683598: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081324  1.93083274  1.75628332]
 [26.18307455  1.18536261  1.76058651]
 [ 3.64264521  2.82599827  1.74201685]
 [ 3.17897156  1.03566899  1.77054981]
 [26.21211148  1.25458603  2.6823437 ]
 [26.15403398  1.11613135  0.83882979]]
       Step     Time          Energy          fmax
LBFGS:    0 18:58:53    -4132.899881   5.90537e-04
LBFGS:    1 18:58:53    -4132.899881   1.18664e-03
LBFGS:    2 18:58:53    -4132.899881   2.37134e-04


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmp9ze16z03
max_memory 21438 MB (current use 1480 MB)
Set gradient conv threshold to 1e-06
init E= 17.6352032209856
  HOMO = -8.36085034253531  LUMO = -4.79179113112029
cycle= 1 E= -139.486979457588  delt

2022-04-23 18:58:54.391831: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 18:58:54.391973: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 18:58:59.119751: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 18:58:59.133203: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081284  1.93083121  1.75628334]
 [26.18307453  1.18536257  1.76058599]
 [ 3.6426433   2.82599088  1.74201697]
 [ 3.17897387  1.03567791  1.77054967]
 [26.21211123  1.25458542  2.68233558]
 [26.15403425  1.116132    0.83883843]]
       Step     Time          Energy          fmax
LBFGS:    0 19:02:07    -4132.992750   1.42696e-03
LBFGS:    1 19:02:07    -4132.992750   2.99444e-03
LBFGS:    2 19:02:07    -4132.992750   1.50973e-03
LBFGS:    3 19:02:07    -4132.992750   4.92331e-03
LBFGS:    4 19:02:07    -4132.992750   2.93569e-05


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmp_ilwdu8d
max_memory 21438 MB (current use 1480 MB)
Set gradient conv threshold to 1e-06
init E= 17.

2022-04-23 19:02:08.470535: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 19:02:08.470678: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 19:02:13.178674: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 19:02:13.191960: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081284  1.93083261  1.75628332]
 [26.18307441  1.18536232  1.76058646]
 [ 3.64264821  2.82600914  1.74201668]
 [ 3.17896896  1.03565825  1.77054998]
 [26.2121119   1.25458701  2.68235486]
 [26.15403369  1.11613066  0.83881868]]
       Step     Time          Energy          fmax
LBFGS:    0 19:05:18    -4132.964973   4.38383e-03
LBFGS:    1 19:05:18    -4132.964975   8.55861e-03
LBFGS:    2 19:05:18    -4132.964973   2.63659e-05


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpqu3wuu1w
max_memory 21438 MB (current use 1480 MB)
Set gradient conv threshold to 1e-06
init E= 17.6334756180812
  HOMO = -8.3607598129053  LUMO = -4.79165312612277
cycle= 1 E= -139.486670446703  delta

2022-04-23 19:05:19.337731: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 19:05:19.337869: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 19:05:24.090671: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 19:05:24.104235: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.4108128   1.93083254  1.75628332]
 [26.1830744   1.1853623   1.76058645]
 [ 3.64266472  2.82607284  1.74201566]
 [ 3.17895249  1.03559462  1.77055099]
 [26.21211397  1.25459194  2.68242042]
 [26.15403163  1.11612575  0.83875313]]
       Step     Time          Energy          fmax
LBFGS:    0 19:08:29    -4132.907120   9.14598e-03
LBFGS:    1 19:08:29    -4132.907127   1.78731e-02
LBFGS:    2 19:08:29    -4132.907117   7.23644e-05


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmp_k_mi725
max_memory 21438 MB (current use 1481 MB)
Set gradient conv threshold to 1e-06
init E= 17.6362534865869
  HOMO = -8.36090566028872  LUMO = -4.79187459432524
cycle= 1 E= -139.487166437412  delt

2022-04-23 19:08:30.980064: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 19:08:30.980208: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 19:08:35.583920: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 19:08:35.597817: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081287  1.93083298  1.75628331]
 [26.18307439  1.18536227  1.76058652]
 [ 3.64263034  2.82594003  1.74201778]
 [ 3.17898679  1.03572699  1.77054888]
 [26.21210968  1.2545817   2.68228386]
 [26.15403594  1.11613602  0.83888962]]
       Step     Time          Energy          fmax
LBFGS:    0 19:11:49    -4131.319944   4.74185e-02
LBFGS:    1 19:11:49    -4131.320132   9.15677e-02
LBFGS:    2 19:11:49    -4131.319874   4.23185e-04


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpocnuus3q
max_memory 21438 MB (current use 1483 MB)
Set gradient conv threshold to 1e-06
init E= 17.6215018224561
  HOMO = -8.36013097143572  LUMO = -4.79069813823646
cycle= 1 E= -139.48453052094  delta

2022-04-23 19:11:50.913882: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 19:11:50.914022: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 19:11:55.512351: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 19:11:55.525976: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.4108122   1.93083059  1.75628335]
 [26.18307436  1.1853622   1.76058615]
 [ 3.64281315  2.82664577  1.74200653]
 [ 3.17880466  1.03502364  1.77056009]
 [26.21213255  1.25463622  2.68300952]
 [26.1540131   1.11608157  0.83816433]]
       Step     Time          Energy          fmax
LBFGS:    0 19:15:13    -4132.994068   4.52172e-02
LBFGS:    1 19:15:13    -4132.994238   8.79810e-02
LBFGS:    2 19:15:13    -4132.994006   2.03136e-03
LBFGS:    3 19:15:13    -4132.994007   7.02991e-03
LBFGS:    4 19:15:13    -4132.994006   2.03404e-05


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpsszcyk9k
max_memory 21438 MB (current use 1486 MB)
Set gradient conv threshold to 1e-06
init E= 17.

2022-04-23 19:15:15.074504: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 19:15:15.074674: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 19:15:19.690768: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 19:15:19.704910: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081254  1.9308327   1.75628332]
 [26.1830743   1.18536207  1.76058648]
 [ 3.64264213  2.82598505  1.74201706]
 [ 3.17897534  1.03568225  1.77054959]
 [26.21211118  1.25458527  2.68233008]
 [26.15403453  1.11613265  0.83884343]]
       Step     Time          Energy          fmax
LBFGS:    0 19:18:45    -4132.827365   3.12275e-02
LBFGS:    1 19:18:45    -4132.827448   6.10399e-02
LBFGS:    2 19:18:45    -4132.827336   1.15057e-04


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpmezvgmjh
max_memory 21438 MB (current use 1619 MB)
Set gradient conv threshold to 1e-06
init E= 17.6258433530698
  HOMO = -8.36035915440123  LUMO = -4.79104427134262
cycle= 1 E= -139.485306387996  delt

2022-04-23 19:18:46.508125: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-23 19:18:46.508300: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-23 19:18:51.652026: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 19:18:51.666503: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed cal

optimizer.py 77: [[ 3.41081248  1.93083256  1.75628332]
 [26.18307429  1.18536205  1.76058646]
 [ 3.64275931  2.82643744  1.74200985]
 [ 3.17885822  1.03523     1.7705568 ]
 [26.21212586  1.25462026  2.68279586]
 [26.15401986  1.11609768  0.83837767]]
       Step     Time          Energy          fmax
LBFGS:    0 19:22:11    -4133.025628   3.69953e-02
LBFGS:    1 19:22:11    -4133.025743   7.20472e-02
LBFGS:    2 19:22:11    -4133.025587   2.13874e-04


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/tmpd98q3qdz
max_memory 21438 MB (current use 1682 MB)
Set gradient conv threshold to 1e-06
init E= 17.6371516192903
  HOMO = -8.3609527933737  LUMO = -4.79194615965879
cycle= 1 E= -139.487326708187  delta