In [1]:
from MQGO import data, main, ML_engine, optimizer, QC_engine 

In [2]:
from deepmd.calculator import DP

2022-04-19 18:21:38.775744: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:21:38.775788: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
setting = {'basis':'6-31g', 'spin':0, 'xc':None, 'restricted':True, 'verbose':4}
geo = main.MLgeomopt(qc_engine='pyscf', ml_engine='deepmd', work_path='./', xyz_path='./water.xyz',**setting)
geo.opt_algorithm = 'lbfgs'
geo.kernel()



******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmpby6g66nu
max_memory 4000 MB (current use 356 MB)
Set gradient conv threshold to 1e-06


OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-15
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #216: KMP_AFFINITY: x2APIC ids not unique.
OMP: Info #216: KMP_AFFINITY: decoding legacy APIC ids.
OMP: Info #216: KMP_AFFINITY: legacy APIC ids not unique.
OMP: Info #220: KMP_AFFINITY: parsing /proc/cpuinfo.
OMP: Info #157: KMP_AFFINITY: 16 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #192: KMP_AFFINITY: 1 socket x 8 cores/socket x 2 threads/core (8 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS p

init E= -151.415122555485
  HOMO = -0.458914611898629  LUMO = 0.101611688525219
cycle= 1 E= -151.868630726732  delta_E= -0.454  |g|= 0.597  |ddm|= 1.64
  HOMO = -0.400323409471753  LUMO = 0.194953131082916
cycle= 2 E= -151.927771207761  delta_E= -0.0591  |g|= 0.357  |ddm|= 0.608
  HOMO = -0.499862289875181  LUMO = 0.180933357043698
cycle= 3 E= -151.95036021667  delta_E= -0.0226  |g|= 0.0355  |ddm|= 0.229
  HOMO = -0.497612927938669  LUMO = 0.187865526656983
cycle= 4 E= -151.950856808118  delta_E= -0.000497  |g|= 0.00594  |ddm|= 0.0375
  HOMO = -0.498863887981172  LUMO = 0.187642464715892
cycle= 5 E= -151.950875581764  delta_E= -1.88e-05  |g|= 0.000688  |ddm|= 0.00925
  HOMO = -0.498920556933567  LUMO = 0.187620019572834
cycle= 6 E= -151.950875817958  delta_E= -2.36e-07  |g|= 0.000198  |ddm|= 0.00111
  HOMO = -0.498975213195489  LUMO = 0.18761647754511
cycle= 7 E= -151.950875827637  delta_E= -9.68e-09  |g|= 5.74e-05  |ddm|= 0.000157
  HOMO = -0.498963904179646  LUMO = 0.187615348330249


2022-04-19 18:21:40.823680: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:21:40.823720: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 1)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-19 18:21:44.122956: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.63802  1.5711   1.76   ]
 [26.36198  1.5711   1.76   ]
 [ 3.95828  2.55412  1.74392]
 [ 2.63613  1.66728  1.76493]
 [26.09174  0.99418  2.56104]
 [26.0955   0.9908   0.96072]]


2022-04-19 18:23:12.369886: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:23:12.370919: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-19 18:23:12.370949: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-19 18:23:12.370976: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Bai-Group): /proc/driver/nvidia/version does not exist


       Step     Time          Energy          fmax
LBFGS:    0 18:23:12    -4134.793820         4.410425
LBFGS:    1 18:23:12    -4136.001188         5.287690
LBFGS:    2 18:23:12    -4134.010644         6.581655
LBFGS:    3 18:23:12    -4134.502865         6.244676
LBFGS:    4 18:23:12    -4134.205117         8.401032
LBFGS:    5 18:23:12    -4134.634620        11.770572
LBFGS:    6 18:23:12    -4134.153726         3.841589
LBFGS:    7 18:23:12    -4134.235974         3.551312
LBFGS:    8 18:23:12    -4134.173842         3.864270
LBFGS:    9 18:23:12    -4134.194479         4.111960
LBFGS:   10 18:23:12    -4134.237536         5.202652
LBFGS:   11 18:23:12    -4134.306374         5.052684
LBFGS:   12 18:23:12    -4134.246089         5.394411
LBFGS:   13 18:23:12    -4134.256417         5.733077
LBFGS:   14 18:23:12    -4134.244313         3.712839
LBFGS:   15 18:23:12    -4134.261027         4.305955
LBFGS:   16 18:23:12    -4134.201744         3.833551
LBFGS:   17 18:23:12    -4134.1

OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23767 thread 16 bound to OS proc set 0
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23769 thread 17 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23770 thread 18 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23772 thread 20 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23771 thread 19 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23773 thread 21 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23775 thread 23 bound to OS proc set 14
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23774 thread 22 bound to OS proc set 12
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23776 thread 24 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23778 thread 26 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23777 thread 25 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 23219 tid 23779 thread 27 bound to OS proc set 7
O

LBFGS:   29 18:23:13    -4132.388197         0.666751
LBFGS:   30 18:23:13    -4132.383166         0.979300
LBFGS:   31 18:23:13    -4132.379980         0.809927
LBFGS:   32 18:23:13    -4132.378453         0.675291
LBFGS:   33 18:23:13    -4132.376677         0.256086
LBFGS:   34 18:23:13    -4132.376422         0.234576
LBFGS:   35 18:23:13    -4132.376270         0.153186
LBFGS:   36 18:23:13    -4132.376231         0.157533
LBFGS:   37 18:23:13    -4132.376212         0.151748
LBFGS:   38 18:23:13    -4132.376204         0.143074
LBFGS:   39 18:23:13    -4132.376181         0.120905
LBFGS:   40 18:23:13    -4132.376144         0.093063
LBFGS:   41 18:23:13    -4132.376089         0.068635
LBFGS:   42 18:23:13    -4132.376051         0.071775
LBFGS:   43 18:23:13    -4132.376041         0.083019
LBFGS:   44 18:23:13    -4132.376040         0.079546
LBFGS:   45 18:23:13    -4132.376040         0.078913
LBFGS:   46 18:23:13    -4132.376040         0.079098
LBFGS:   47 18:23:13    -413

2022-04-19 18:23:13.770764: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:23:13.770805: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 2)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-19 18:23:17.034825: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41081013  1.93083268  1.75628334]
 [26.18307343  1.18536022  1.76058653]
 [ 4.0248681   2.50365278  1.74422293]
 [ 2.79675177  1.35801454  1.76834373]
 [26.16062758  1.14298278  2.5990591 ]
 [26.20551898  1.227737    0.92211437]]
       Step     Time          Energy          fmax
LBFGS:    0 18:25:04    -4133.852808         7.659449
LBFGS:    1 18:25:04    -4138.924547        15.373663
LBFGS:    2 18:25:04    -4132.237551         1.500544
LBFGS:    3 18:25:04    -4132.160268         0.308790
LBFGS:    4 18:25:04    -4132.156591         0.023708
LBFGS:    5 18:25:04    -4132.156573         0.011637
LBFGS:    6 18:25:04    -4132.156580         0.034697
LBFGS:    7 18:25:04    -4132.156572         0.000012
main.py 94: QC_coords1 [[ 6.44549759  3.64874536  3.3188945 ]
 [49.47883789  2.2400062   3.32702666]
 [ 7.76926647  4.88361471  3.29289501]
 [ 5.12172622  2.41387851  3.34489398]
 [49.43044981  2.1486502   5.13458093]
 [49.52722538  2.33136088  1.51947226]]


*****

/home/jingheng/ase/ase/io/extxyz.py:1001: UserWarning: write_xyz() overwriting array "forces" present in atoms.arrays with stored results from calculator
  warnings.warn('write_xyz() overwriting array "{0}" present '


--------------- RHF gradients ---------------
         x                y                z
0 O     0.0000021730    -0.0000000469    -0.0000001208
1 O     0.0000011379    -0.0000026241     0.0000000509
2 H     0.0277721175     0.0259082147    -0.0005454210
3 H    -0.0277743062    -0.0259081565     0.0005455409
4 H    -0.0010157385    -0.0019153498     0.0379229043
5 H     0.0010146163     0.0019179627    -0.0379229542
----------------------------------------------

			###########################################
			###      Optimization cycle:     3      ###
			###########################################
			


2022-04-19 18:25:04.770970: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:25:04.771014: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 3)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-19 18:25:08.040461: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41081044  1.93083289  1.75628333]
 [26.18307344  1.18536023  1.76058669]
 [ 4.11131876  2.58429761  1.742525  ]
 [ 2.7103008   1.2773695   1.77004167]
 [26.15746756  1.13701672  2.71710322]
 [26.20867899  1.23370305  0.80407009]]
       Step     Time          Energy          fmax
LBFGS:    0 18:27:15    -4132.789919         1.978249
LBFGS:    1 18:27:15    -4133.091363         3.301680
LBFGS:    2 18:27:15    -4132.666085         0.651868
LBFGS:    3 18:27:15    -4132.654822         0.156298
LBFGS:    4 18:27:15    -4132.654094         0.005274
LBFGS:    5 18:27:15    -4132.654093         0.000486
LBFGS:    6 18:27:15    -4132.654093         0.001719
LBFGS:    7 18:27:15    -4132.654093         0.000046
main.py 94: QC_coords1 [[ 6.4454974   3.64874561  3.31889449]
 [49.47883784  2.24000608  3.32702667]
 [ 7.72374997  4.8411548   3.29378898]
 [ 5.16724292  2.45633817  3.34400002]
 [49.43211364  2.15179151  5.0724282 ]
 [49.52556159  2.32821969  1.58162498]]


*****

2022-04-19 18:27:16.450399: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:27:16.450439: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 4)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-19 18:27:19.773924: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41081034  1.93083302  1.75628333]
 [26.18307341  1.18536017  1.76058669]
 [ 4.08723246  2.56182879  1.74299807]
 [ 2.7343872   1.29983818  1.7695686 ]
 [26.15834803  1.13867903  2.68421341]
 [26.20779855  1.2320408   0.8369599 ]]
       Step     Time          Energy          fmax
LBFGS:    0 18:29:48    -4132.751646         0.016987
LBFGS:    1 18:29:48    -4132.751670         0.033298
LBFGS:    2 18:29:48    -4132.751637         0.000049
main.py 94: QC_coords1 [[ 6.44549706  3.64874529  3.3188945 ]
 [49.47883785  2.24000609  3.32702651]
 [ 7.72340093  4.8408292   3.29379584]
 [ 5.1675923   2.45666407  3.34399315]
 [49.43212635  2.15181549  5.07195383]
 [49.52554888  2.3281957   1.58209952]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf =

2022-04-19 18:29:49.117087: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:29:49.117128: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 5)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-19 18:29:52.440126: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41081016  1.93083285  1.75628333]
 [26.18307341  1.18536017  1.76058661]
 [ 4.08704776  2.56165649  1.7430017 ]
 [ 2.73457208  1.30001064  1.76956497]
 [26.15835475  1.13869172  2.68396238]
 [26.20779183  1.23202811  0.83721101]]
       Step     Time          Energy          fmax
LBFGS:    0 18:32:46    -4132.769429         0.005689
LBFGS:    1 18:32:46    -4132.769432         0.011177
LBFGS:    2 18:32:46    -4132.769428         0.000192
main.py 94: QC_coords1 [[ 6.4454989   3.64874699  3.31889445]
 [49.47883782  2.24000604  3.32702732]
 [ 7.72351663  4.84093713  3.29379358]
 [ 5.16747476  2.45655442  3.34399546]
 [49.43212209  2.15180746  5.07211267]
 [49.52555316  2.32820377  1.58193987]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf =

2022-04-19 18:32:46.834482: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:32:46.834522: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-19 18:32:50.139890: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:32:50.142963: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41081113  1.93083376  1.75628331]
 [26.1830734   1.18536015  1.76058704]
 [ 4.08710899  2.56171361  1.7430005 ]
 [ 2.73450988  1.29995262  1.76956619]
 [26.1583525   1.13868747  2.68404644]
 [26.20779409  1.23203238  0.83712653]]
       Step     Time          Energy          fmax
LBFGS:    0 18:36:05    -4132.878560         0.011761
LBFGS:    1 18:36:05    -4132.878572         0.023150
LBFGS:    2 18:36:05    -4132.878556         0.001043
LBFGS:    3 18:36:05    -4132.878556         0.003601
LBFGS:    4 18:36:05    -4132.878556         0.000002
main.py 94: QC_coords1 [[ 6.44549732  3.64874559  3.31889448]
 [49.47883784  2.24000606  3.32702664]
 [ 7.72327693  4.8407135   3.29379829]
 [ 5.16771603  2.45677947  3.34399072]
 [49.43213088  2.15182405  5.07178463]
 [49.52554436  2.32818717  1.5822686 ]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_st

2022-04-19 18:36:06.407080: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:36:06.407124: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-19 18:36:09.718500: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:36:09.721438: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.4108103   1.93083301  1.75628333]
 [26.18307341  1.18536016  1.76058668]
 [ 4.08698215  2.56159527  1.74300299]
 [ 2.73463756  1.30007171  1.76956368]
 [26.15835715  1.13869625  2.68387285]
 [26.20778944  1.23202359  0.83730048]]
       Step     Time          Energy          fmax
LBFGS:    0 18:39:26    -4133.002885         0.003129
LBFGS:    1 18:39:26    -4133.002886         0.006103
LBFGS:    2 18:39:26    -4133.002884         0.000005
main.py 94: QC_coords1 [[ 6.44549734  3.6487456   3.31889449]
 [49.47883784  2.24000606  3.32702665]
 [ 7.72321199  4.84065291  3.29379956]
 [ 5.16778098  2.45684005  3.34398944]
 [49.43213326  2.15182854  5.07169596]
 [49.525542    2.32818268  1.58235727]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf =

2022-04-19 18:39:27.002301: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:39:27.002341: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-19 18:39:30.305296: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:39:30.307895: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.4108103   1.93083302  1.75628333]
 [26.18307341  1.18536016  1.76058668]
 [ 4.08694778  2.5615632   1.74300367]
 [ 2.73467193  1.30010376  1.76956301]
 [26.15835841  1.13869862  2.68382592]
 [26.20778818  1.23202122  0.83734741]]
       Step     Time          Energy          fmax
LBFGS:    0 18:42:47    -4132.938368         0.135182
LBFGS:    1 18:42:47    -4132.939898         0.260720
LBFGS:    2 18:42:47    -4132.937813         0.002030
LBFGS:    3 18:42:47    -4132.937813         0.000044
main.py 94: QC_coords1 [[ 6.44549703  3.64874545  3.3188945 ]
 [49.47883783  2.24000602  3.32702665]
 [ 7.7203816   4.83801253  3.29385516]
 [ 5.17061167  2.45948056  3.34393385]
 [49.43223674  2.15202389  5.06783097]
 [49.52543853  2.32798736  1.58622226]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF 

2022-04-19 18:42:47.653662: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:42:47.653705: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-19 18:42:50.930265: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:42:50.933374: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41081014  1.93083294  1.75628333]
 [26.1830734   1.18536014  1.76058668]
 [ 4.08545     2.56016598  1.74303309]
 [ 2.73616986  1.30150106  1.76953359]
 [26.15841317  1.138802    2.68178066]
 [26.20773343  1.23191786  0.83939267]]
       Step     Time          Energy          fmax
LBFGS:    0 18:46:07    -4133.012082         0.147517
LBFGS:    1 18:46:07    -4133.013930         0.291347
LBFGS:    2 18:46:08    -4133.011436         0.002349
LBFGS:    3 18:46:08    -4133.011436         0.000736
LBFGS:    4 18:46:08    -4133.011436         0.002676
LBFGS:    5 18:46:08    -4133.011436         0.000003
main.py 94: QC_coords1 [[ 6.44549715  3.64874576  3.31889449]
 [49.4788378   2.24000597  3.32702664]
 [ 7.72341481  4.84084195  3.29379559]
 [ 5.16757833  2.45665083  3.34399343]
 [49.43212588  2.15181459  5.07197279]
 [49.52554942  2.32819672  1.58208044]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift fa

2022-04-19 18:46:08.612200: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 18:46:08.612242: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-19 18:46:11.906417: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 18:46:11.909473: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.4108102   1.93083311  1.75628333]
 [26.18307339  1.18536011  1.76058668]
 [ 4.08705511  2.56166324  1.74300156]
 [ 2.73456469  1.30000363  1.76956512]
 [26.1583545   1.13869124  2.68397242]
 [26.20779211  1.23202865  0.83720092]]
       Step     Time          Energy          fmax
LBFGS:    0 18:49:27    -4133.047388         0.003757
LBFGS:    1 18:49:27    -4133.047389         0.007336
LBFGS:    2 18:49:27    -4133.047388         0.000003
main.py 94: QC_coords1 [[ 6.44549715  3.64874579  3.31889449]
 [49.4788378   2.24000596  3.32702665]
 [ 7.72349269  4.84091458  3.29379405]
 [ 5.16750045  2.45657816  3.34399497]
 [49.43212303  2.15180921  5.07207914]
 [49.52555226  2.3282021   1.58197411]]


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf =

In [4]:
from MQGO import optimizer
Opt = optimizer.Optimizer(xyz_path="water0.xyz",
									work_path="./",
									ml_engine='deepmd',
									outter_cycle=1,
									algorithm='bfgs',
									max_opt_cycle=100)
atom = Opt.ase_read_xyz()
print(atom.get_positions())
atom.calc = DP(model='graph.pb')
print(atom.get_potential_energy())
force0_ml = atom.get_forces()
print(atom.get_forces())

[[ 3.63802  1.5711   1.76   ]
 [26.36198  1.5711   1.76   ]
 [ 3.95828  2.55412  1.74392]
 [ 2.63613  1.66728  1.76493]
 [26.09174  0.99418  2.56104]
 [26.0955   0.9908   0.96072]]
-4132.799365865741
[[ 1.74271480e+00 -4.02384015e+00  4.66008093e-02]
 [ 1.86615095e+00  4.02352386e+00 -1.68861396e-02]
 [ 5.33263437e-01  3.28007431e+00 -5.02850158e-02]
 [-2.27597824e+00  7.43765843e-01  3.68420650e-03]
 [-9.39618606e-01 -2.01139593e+00  2.02486619e+00]
 [-9.26532345e-01 -2.01212793e+00 -2.00798005e+00]]


In [5]:
import numpy as np
forces = np.loadtxt('raw/force.raw')
force0_qc = forces[0].reshape((6,3))
print(force0_qc)

[[ 1.73445043e+00 -4.04231476e+00  4.69214939e-02]
 [ 1.86311912e+00  4.01780156e+00 -1.71757040e-02]
 [ 5.53645372e-01  3.30830811e+00 -5.08197707e-02]
 [-2.28815565e+00  7.34015571e-01  3.89837807e-03]
 [-9.38164644e-01 -2.00861169e+00  2.04263408e+00]
 [-9.24894634e-01 -2.00919880e+00 -2.02545848e+00]]


In [6]:
delta = force0_qc-force0_ml
with open('debug_force.txt', 'a') as file:
    for i in range(0, len(force0_qc)):
        for j in range(0, 3):
            file.write('%24.18f'%delta[i][j])
        file.write('\n')
    file.write('\n')

In [7]:
print(max(delta.flatten()))

0.028233807265405364
