In [1]:
from MQGO import data, main, ML_engine, optimizer, QC_engine 
from deepmd.calculator import DP
import subprocess
import numpy as np

2022-04-22 18:24:33.283621: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:24:33.283685: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
import json
with open('./input0.json', 'r') as file:
    json_setting = json.load(file)
    
keys_1 = ['learning_rate','training']
keys_2 = ['decay_steps','numb_steps']

In [ ]:
d_steps = [3000, 4000]
tot_steps = [4000, 5000, 6000]
subprocess.run('cp water0.xyz water.xyz', shell=True)

index = 0
for i in d_steps:
    for j in tot_steps:
        json_setting['learning_rate']['decay_steps'] = i
        json_setting['training']['numb_steps'] = j
        print(json_setting['learning_rate']['decay_steps'])
        with open('./input.json', 'w+') as js:
            json.dump(json_setting, js, indent=4)
        
        setting = {'basis':'6-31g', 'spin':0, 'xc':None, 'restricted':True, 'verbose':4}
        geo = main.MLgeomopt(qc_engine='pyscf', ml_engine='deepmd', work_path='./', xyz_path='./water.xyz',**setting)
        geo.opt_algorithm = 'lbfgs'
        geo.debug = True
        geo.kernel()
        
        Opt = optimizer.Optimizer(xyz_path="water0.xyz",
									work_path="./",
									ml_engine='deepmd',
									outter_cycle=1,
									algorithm='lbfgs',
									max_opt_cycle=100)
        atom0 = Opt.ase_read_xyz()
        atom0.calc = DP(model='graph.pb')
        print(atom0.get_potential_energy())
        force0_ml = atom0.get_forces()

        forces = np.loadtxt('raw/force.raw')
        force0_qc = forces[0].reshape((6,3))

        delta = force0_qc-force0_ml
        with open('debug_diff_force.txt', 'a') as file:
            for i in range(0, len(force0_qc)):
                for j in range(0, 3):
                    file.write('%24.18f'%delta[i][j])
                file.write('\n')
            file.write('\n')
            
        subprocess.run('cp water0.xyz water.xyz', shell=True)
        subprocess.run('rm input.json', shell=True)

3000


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmpd36wio0m
max_memory 4000 MB (current use 356 MB)
Set gradient conv threshold to 1e-06
init E= -151.415122555485
  HOMO = -0.458914611898627  LUMO = 0.101611688525217
cycle= 1 E= -151.868630726732  delta_E= -0.454  |g|= 0.597  |ddm|= 1.64
  HOMO = -0.400323409471752  LUMO = 0.194953131082914
cycle= 2 E= -151.927771207761  delta_E= -0.0591  |g|= 0.357  |ddm|= 0.608
  HOMO = -0.499862289875181  LUMO = 0.180933357043696
cycle= 3 E= -151.95036021667  delta_E= -0.0226  |g|= 0.0355  |ddm|= 0.229
  HOMO = -0.497612927938672  LUMO = 0.187865526656978
cycle= 4 E= -151.950856808118  delta_E= -0.000497  |g|= 0.0059

OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-15
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #216: KMP_AFFINITY: x2APIC ids not unique.
OMP: Info #216: KMP_AFFINITY: decoding legacy APIC ids.
OMP: Info #216: KMP_AFFINITY: legacy APIC ids not unique.
OMP: Info #220: KMP_AFFINITY: parsing /proc/cpuinfo.
OMP: Info #157: KMP_AFFINITY: 16 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #192: KMP_AFFINITY: 1 socket x 8 cores/socket x 2 threads/core (8 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS p

  HOMO = -0.498963904179651  LUMO = 0.187615348330241
cycle= 8 E= -151.950875829917  delta_E= -2.28e-09  |g|= 1.17e-05  |ddm|= 0.00012
  HOMO = -0.49896196507004  LUMO = 0.187614886419017
cycle= 9 E= -151.95087583003  delta_E= -1.13e-10  |g|= 1.35e-06  |ddm|= 3.23e-05
  HOMO = -0.498961881531365  LUMO = 0.187614670626274
cycle= 10 E= -151.950875830031  delta_E= -7.96e-13  |g|= 2.51e-07  |ddm|= 2.62e-06
  HOMO = -0.498961918333588  LUMO = 0.187614654845974
Extra cycle  E= -151.950875830031  delta_E= 1.14e-13  |g|= 9.65e-08  |ddm|= 2.65e-07
converged SCF energy = -151.950875830031


******** <class 'pyscf.grad.rhf.Gradients'> for <class 'pyscf.scf.hf.RHF'> ********
unit = Eh/Bohr
max_memory 4000 MB (current use 362 MB)
--------------- RHF gradients ---------------
         x                y                z
0 O     0.0337296910    -0.0786105069     0.0009124778
1 O     0.0362318987     0.0781338011    -0.0003340143
2 H     0.0107666884     0.0643363502    -0.0009882872
3 H    -0.0444975

2022-04-22 18:24:35.709079: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:24:35.709123: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 1)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-22 18:24:39.235298: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.63802  1.5711   1.76   ]
 [26.36198  1.5711   1.76   ]
 [ 3.95828  2.55412  1.74392]
 [ 2.63613  1.66728  1.76493]
 [26.09174  0.99418  2.56104]
 [26.0955   0.9908   0.96072]]


2022-04-22 18:25:43.928294: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:25:43.929483: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-22 18:25:43.929515: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-22 18:25:43.929562: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Bai-Group): /proc/driver/nvidia/version does not exist


       Step     Time          Energy          fmax
LBFGS:    0 18:25:44    -4134.792468         4.421026
LBFGS:    1 18:25:44    -4135.993167         5.252436
LBFGS:    2 18:25:44    -4133.885224         5.825335
LBFGS:    3 18:25:44    -4134.438276         6.960483
LBFGS:    4 18:25:44    -4133.855313         5.394538
LBFGS:    5 18:25:44    -4133.841207         4.534503
LBFGS:    6 18:25:44    -4133.886179         3.938305
LBFGS:    7 18:25:44    -4133.518688         5.670696
LBFGS:    8 18:25:44    -4132.847205         6.831991
LBFGS:    9 18:25:44    -4132.909359         6.763676
LBFGS:   10 18:25:44    -4132.948503         5.808409
LBFGS:   11 18:25:44    -4132.981925         6.693745
LBFGS:   12 18:25:44    -4132.969709         6.080101
LBFGS:   13 18:25:44    -4132.984731         6.297816
LBFGS:   14 18:25:44    -4132.951036         5.912868
LBFGS:   15 18:25:44    -4132.943880         5.983281
LBFGS:   16 18:25:44    -4132.957398         6.294843
LBFGS:   17 18:25:44    -4132.9

OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11288 thread 16 bound to OS proc set 0
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11290 thread 17 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11291 thread 18 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11292 thread 19 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11293 thread 20 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11295 thread 22 bound to OS proc set 12
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11294 thread 21 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11296 thread 23 bound to OS proc set 14
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11299 thread 26 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11297 thread 24 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11298 thread 25 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 10689 tid 11301 thread 28 bound to OS proc set 9
O

LBFGS:   28 18:25:44    -4132.505905         0.184511
LBFGS:   29 18:25:44    -4132.505751         0.109064
LBFGS:   30 18:25:44    -4132.505551         0.092172
LBFGS:   31 18:25:44    -4132.505021         0.048717
LBFGS:   32 18:25:44    -4132.504932         0.018109
LBFGS:   33 18:25:44    -4132.504925         0.003720
LBFGS:   34 18:25:44    -4132.504924         0.000757
LBFGS:   35 18:25:44    -4132.504924         0.000078


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmpgtqhsf_p
max_memory 4000 MB (current use 549 MB)
Set gradient conv threshold to 1e-06
init E= -152.134773034599
  HOMO = -0.514613340927601  LUMO = 0.136022138624633
cycle= 1 E= -151.

2022-04-22 18:25:45.194993: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:25:45.195033: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 2)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-22 18:25:48.498375: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41080778  1.93083444  1.75628333]
 [26.18307409  1.18536164  1.76058673]
 [ 3.89030487  2.61720357  1.7434453 ]
 [ 2.93131735  1.24446199  1.76912137]
 [26.14497865  1.10920272  2.59361391]
 [26.22116726  1.26151564  0.92755936]]
       Step     Time          Energy          fmax
LBFGS:    0 18:27:05    -4133.672630         7.991011
LBFGS:    1 18:27:05    -4139.459937        17.348146
LBFGS:    2 18:27:05    -4132.057048         1.697678
LBFGS:    3 18:27:05    -4131.966089         0.425009
LBFGS:    4 18:27:05    -4131.959513         0.036713
LBFGS:    5 18:27:05    -4131.959473         0.021499
LBFGS:    6 18:27:05    -4131.959494         0.065654
LBFGS:    7 18:27:05    -4131.959470         0.000054


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100


/home/jingheng/ase/ase/io/extxyz.py:1001: UserWarning: write_xyz() overwriting array "forces" present in atoms.arrays with stored results from calculator
  warnings.warn('write_xyz() overwriting array "{0}" present '


--------------- RHF gradients ---------------
         x                y                z
0 O     0.0000033765    -0.0000006513    -0.0000002040
1 O    -0.0000006799    -0.0000029818    -0.0000000019
2 H     0.0186143644     0.0266484602    -0.0004983316
3 H    -0.0186177458    -0.0266477991     0.0004985338
4 H    -0.0014785500    -0.0029550912     0.0323401189
5 H     0.0014792348     0.0029580632    -0.0323401151
----------------------------------------------


******** <class 'pyscf.grad.rhf.Gradients'> for <class 'pyscf.scf.hf.RHF'> ********
unit = Eh/Bohr
max_memory 4000 MB (current use 732 MB)
--------------- RHF gradients ---------------
         x                y                z
0 O     0.0000033765    -0.0000006513    -0.0000002040
1 O    -0.0000006799    -0.0000029818    -0.0000000019
2 H     0.0186143644     0.0266484602    -0.0004983316
3 H    -0.0186177458    -0.0266477991     0.0004985338
4 H    -0.0014785500    -0.0029550912     0.0323401189
5 H     0.0014792348     

2022-04-22 18:27:05.846129: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:27:05.846187: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 3)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-22 18:27:09.152157: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41080771  1.93083503  1.75628332]
 [26.18307421  1.18536189  1.7605869 ]
 [ 3.95638335  2.71179119  1.74167611]
 [ 2.86523894  1.14987378  1.77089057]
 [26.13972899  1.09870781  2.70840959]
 [26.22641681  1.2720103   0.81276351]]
       Step     Time          Energy          fmax
LBFGS:    0 18:28:40    -4132.685526         1.676553
LBFGS:    1 18:28:40    -4132.905560         2.879436
LBFGS:    2 18:28:40    -4132.595278         0.409796
LBFGS:    3 18:28:40    -4132.590629         0.080328
LBFGS:    4 18:28:40    -4132.590438         0.002077
LBFGS:    5 18:28:40    -4132.590438         0.002332
LBFGS:    6 18:28:40    -4132.590438         0.006322
LBFGS:    7 18:28:40    -4132.590438         0.000197


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100


2022-04-22 18:28:41.573415: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:28:41.573459: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 4)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-22 18:28:44.854021: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41080802  1.9308344   1.75628333]
 [26.18307402  1.18536149  1.76058677]
 [ 3.94067528  2.68930642  1.74209667]
 [ 2.8809467   1.17235917  1.77047   ]
 [26.14097715  1.1012031   2.68111745]
 [26.22516883  1.26951541  0.84005578]]
       Step     Time          Energy          fmax
LBFGS:    0 18:30:30    -4132.815888         0.032173
LBFGS:    1 18:30:30    -4132.815974         0.062860
LBFGS:    2 18:30:30    -4132.815857         0.000269


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmp0l2_teyc
max_memory 4000 MB (current use 1096 MB)
Set gradient conv threshold to 1e-06
init E= -151.767770755677
  HOMO = -0.484241484943977  LUMO = 0

2022-04-22 18:30:31.246636: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:30:31.246675: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
/home/jingheng/venv/lib/python3.9/site-packages/deepmd/utils/data_system.py:158: UserWarning: system ./raw/ required batch size is larger than the size of the dataset raw/set.000 (6 > 5)
  warnings.warn("system %s required batch size is larger than the size of the dataset %s (%d > %d)" % \
2022-04-22 18:30:34.586398: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Ne

optimizer.py 77: [[ 3.41080903  1.93083584  1.7562833 ]
 [26.183074    1.18536145  1.76058721]
 [ 3.94039874  2.68891057  1.74210407]
 [ 2.88122223  1.17275358  1.77046262]
 [26.14099889  1.10124655  2.68064214]
 [26.22514711  1.269472    0.84053065]]
       Step     Time          Energy          fmax
LBFGS:    0 18:32:36    -4132.882499         0.000976
LBFGS:    1 18:32:36    -4132.882499         0.002115
LBFGS:    2 18:32:36    -4132.882499         0.001308
LBFGS:    3 18:32:36    -4132.882499         0.003707
LBFGS:    4 18:32:36    -4132.882499         0.000013


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmphqu74y6s
max_memory 4000 MB (current use 1

2022-04-22 18:32:37.401378: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:32:37.401419: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:32:40.745066: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:32:40.748203: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41080821  1.93083452  1.75628332]
 [26.18307399  1.18536143  1.76058682]
 [ 3.9403919   2.68890085  1.74210425]
 [ 2.88122989  1.17276462  1.77046241]
 [26.14099947  1.10124771  2.68062975]
 [26.22514654  1.26947086  0.84054343]]
       Step     Time          Energy          fmax
LBFGS:    0 18:35:00    -4132.840950         0.002247
LBFGS:    1 18:35:00    -4132.840951         0.004405
LBFGS:    2 18:35:00    -4132.840950         0.000048


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmpqofpnx9x
max_memory 4000 MB (current use 1326 MB)
Set gradient conv threshold to 1e-06
init E= -151.767684214629
  HOMO = -0.484235190046324  LUMO = 0

2022-04-22 18:35:01.492839: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:35:01.492894: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:35:05.125577: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:35:05.128554: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.4108084   1.93083478  1.75628332]
 [26.18307399  1.18536142  1.76058687]
 [ 3.94041096  2.68892814  1.74210374]
 [ 2.88121064  1.17273707  1.77046293]
 [26.14099795  1.10124467  2.68066301]
 [26.22514806  1.26947391  0.84051013]]
       Step     Time          Energy          fmax
LBFGS:    0 18:37:26    -4132.801698         0.050400
LBFGS:    1 18:37:26    -4132.801912         0.098513
LBFGS:    2 18:37:26    -4132.801622         0.000434


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmp2jr80_5d
max_memory 4000 MB (current use 1326 MB)
Set gradient conv threshold to 1e-06
init E= -151.764545372713
  HOMO = -0.484007175733497  LUMO = 0

2022-04-22 18:37:27.492940: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:37:27.492991: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:37:30.982635: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:37:30.985300: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41080728  1.93083312  1.75628335]
 [26.18307399  1.18536142  1.76058658]
 [ 3.94084357  2.68954743  1.74209216]
 [ 2.88077915  1.17211944  1.77047448]
 [26.14096362  1.10117605  2.68141375]
 [26.22518238  1.26954253  0.83975968]]
       Step     Time          Energy          fmax
LBFGS:    0 18:39:51    -4131.882016         0.075332
LBFGS:    1 18:39:51    -4131.882491         0.146472
LBFGS:    2 18:39:51    -4131.881845         0.001552
LBFGS:    3 18:39:51    -4131.881845         0.005293
LBFGS:    4 18:39:51    -4131.881845         0.000576
LBFGS:    5 18:39:51    -4131.881845         0.000239


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/wat

2022-04-22 18:39:52.380964: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:39:52.381004: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:39:55.765119: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:39:55.767637: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41080883  1.93083487  1.75628332]
 [26.18307389  1.18536121  1.76058689]
 [ 3.94019314  2.68861661  1.74210957]
 [ 2.88142803  1.17304851  1.7704571 ]
 [26.14101528  1.10127934  2.68028495]
 [26.22513082  1.26943945  0.84088817]]
       Step     Time          Energy          fmax
LBFGS:    0 18:42:15    -4132.997344         0.036687
LBFGS:    1 18:42:15    -4132.997457         0.071825
LBFGS:    2 18:42:15    -4132.997304         0.000701
LBFGS:    3 18:42:15    -4132.997304         0.002548
LBFGS:    4 18:42:15    -4132.997304         0.000035


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmpczwkyhza
max_memory 4000 MB (current use 1

2022-04-22 18:42:16.019497: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:42:16.019555: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:42:19.394617: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:42:19.397882: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41080857  1.93083424  1.75628333]
 [26.18307385  1.18536112  1.76058679]
 [ 3.94050796  2.68906738  1.74210114]
 [ 2.88111347  1.17259837  1.77046552]
 [26.1409903   1.1012294   2.68083171]
 [26.22515584  1.26948948  0.84034151]]
       Step     Time          Energy          fmax
LBFGS:    0 18:44:39    -4132.929354         0.098348
LBFGS:    1 18:44:39    -4132.930167         0.190907
LBFGS:    2 18:44:39    -4132.929063         0.001100
LBFGS:    3 18:44:39    -4132.929063         0.000308


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/jingheng/ML_QC_GEOM_OPT/test/water/dimer/tmpzwpdec01
max_memory 4000 MB (current use 1372 MB)
Set gradient conv threshold to 1e-06
init E= -

2022-04-22 18:44:39.700893: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:44:39.700934: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:44:43.170850: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:44:43.173146: W tensorflow/stream_executor/platform/default/dso_loader

optimizer.py 77: [[ 3.41080978  1.93083551  1.7562833 ]
 [26.18307376  1.18536093  1.76058692]
 [ 3.93966163  2.68785613  1.7421238 ]
 [ 2.88195859  1.17380834  1.77044289]
 [26.14105753  1.10136382  2.67936237]
 [26.22508869  1.26935525  0.84181072]]
       Step     Time          Energy          fmax
LBFGS:    0 18:47:01    -4132.987371         0.091044
LBFGS:    1 18:47:01    -4132.988070         0.178912
LBFGS:    2 18:47:01    -4132.987124         0.001804
LBFGS:    3 18:47:01    -4132.987124         0.006450
LBFGS:    4 18:47:01    -4132.987124         0.001162
LBFGS:    5 18:47:01    -4132.987124         0.000743
LBFGS:    6 18:47:01    -4132.987124         0.000060


******** <class 'pyscf.scf.hf.RHF'> ********
method = RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to sa

2022-04-22 18:47:02.442280: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-22 18:47:02.442322: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2022-04-22 18:47:05.782996: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 18:47:05.785498: W tensorflow/stream_executor/platform/default/dso_loader